services:
  plsdatagrab:
    build: .
    image: plsdatagrab:v1
    container_name: plsdatagrab
    hostname: plsdatagrab
    restart: always
    environment:
      - INFLUX_HOST_PORT=https://my.influx.com:8086
      - INFLUX_ORG=myorg
      - INFLUX_BUCKET=pls 
      - INFLUX_KEY=mykey==
      - PLS_PRICE_URI=https://pro-api.coinmarketcap.com/v2/cryptocurrency/quotes/latest?id=11145
      - PLS_PRICE_API_KEY=mykey==
      - PLS_LAUNCH_URI=https://launchpad.pulsechain.com/en/
      - CRON_SCHEDULE=0 * * * *
      - CRON_PRICE=*/5 * * * *
    # Recommended to setup a volume for the settings file
    # networks setup depends on intercomm between other container stacks. Depends on declaration near the end of this file.
    # networks:
    #   my_network: # this is the network name
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"    

# setup network if required. This is for intercomm between container stacks usually.
# networks:
#   my_network:
#     external: True